### ISSUE TITLE
cv-content element

### ISSUE THREAD

**Issue by hajarghaem** [FontoXML/fontoxml-development-tools-module-localization#1]
Dear,
it is not an issue but a question regarding the way fontoxml works. I'd like to know what happen when we want to change/edit a content in fontoxml editor. I see that the code changes. In fact when I select the current content it is inside:
<cv-content><cv-inline-object node-id="7" cv-layout="inline"><span class="fontoxml-text-placeholder" operation-name="select-node" operation-context-node-id="7" contenteditable="false">Type your content</span><chrome-selection-workaround></chrome-selection-workaround></cv-inline-object></cv-content>

but when I add a new content then it changes:

<cv-content>new cuntent<span class="cursor">​​</span></cv-content>

I want to know what action happens there and what is the reason for this change.

Thanks in advance,
Kind regards,
Hajar

**Comment by ThomasBrekelmans** [comment]
Hi Hajar,

I'm afraid I don't quite understand your question. I think you might have a question for your support contact at FontoXML. I don't think this question is related to this repository so I'm going to close this issue for now.

Please send your inquiry to your contact at FontoXML if you need further assistance.

Kind regards,
Thomas Brekelmans
Team Lead @ FontoXML (Platform/SDK development)

**Comment by hajarghaem** [comment]
Hi @ThomasBrekelmans,
Thanks for your fast response.
I actually use selenuim webriverio to test fontoxml functioanlity. I saw that in the code, when I edit a content in fontoxml, then some elements are removed. I want to find what action causes this removing. 

Do you know if there is a good tutorial for fontoxml coding?

Kind regards,
Hajar

**Comment by ThomasBrekelmans** [comment]
Testing FontoXML with Selenium isn't a really good fit, especially for the content view (the part on the left with the content of the document(s) your authoring).
This is because the underlying HTML DOM is directly tied to the XML DOM of the authored document. 

You could simplify the underlying architecture by saying, whatever you see in the content view is a direct function on the XML DOM. (Which can be configured with a set of API's we call the CVK, content visualization kit).

This is strictly enforced by the JavaScript core of the editor, i.e. it's "not allowed" to modify the HTML DOM directly. So you can't simulate typing in the editor by inserting text nodes at a certain place.

Instead you could write a package in your own editor that exposes a method through either our IframeCommunicationManager or store it on a global object which calls the "insert-text" operation (using the OperationsManager).
You could then call this method from your selenium tests and asserts the expected results afterwards.

Could you let me know which customer/partner your working for? Which Fonto application?
Perhaps one of your support contacts here at FontoXML could help you more directly.
